apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: amir-dev

resources:
  - namespace.yaml
#  - ../../base



commonLabels:
  environment: dev
  owner: amir
  app: testapp


configMapGenerator:
 
- name: aplication-variables
  literals:	
  - JAVA_HOME=/opt/java/jdk
  - JAVA_TOOL_OPTIONS=-agentlib:hprof
  - ENV=dev
  - debug_mode=error
  - log_level=info