version: 2.1
jobs:
  install-node-example:
    docker:
      - image: circleci/node
    resource_class: small
    steps:
      - checkout

      - run: node --version

  print-a-message:
    docker:
      - image: cimg/base:2022.03
    parameters:
      message:
        type: string
    steps:
      - run: echo << parameters.message >>

  print-0-message:
    docker:
      - image: cimg/base:2022.03

    steps:
      - run: echo 123

workflows:
  build-test-and-deploy:
    jobs:
      - install-node-example
      - print-0-message
 