version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    resource_class: small
    steps:
      - checkout

      - run: node --version


# workflows:
#   test_my_app:
#     jobs:
#       - install-node-example