version: 2.1
jobs:
  install-node-example:
    docker:
      - image: circleci/node
    resource_class: small
    steps:
      - checkout

      - run: node --version

  print-a-message:
    docker:
      - image: cimg/base:2022.03
    parameters:
      message:
        type: string
    steps:
      - run: echo << parameters.message >>



workflows:
  test_my_app:
    jobs:
      - install-node-example
      - print-a-message
          message: Hello!